name: environment/wazuh/0

decoders:
  # First level decoders (internal)
  - decoder/internal-ossec-message/0
  - decoder/internal-localfile/0
  - decoder/internal-rsyslog/0
  - decoder/internal-hostinfo/0
  - decoder/internal-dbsync/0
  - decoder/internal-syscheck/0
  - decoder/internal-rootcheck/0
  - decoder/internal-syscollector/0
  - decoder/internal-ciscat/0
  - decoder/internal-windows/0
  - decoder/internal-sca/0
  - decoder/internal-secure/0
  - decoder/internal-upgrade/0

  # Wazuh agent decoders (internal)
  - decoder/dbsync/0
  - decoder/fim/0
  - decoder/fim-event/0
  - decoder/fim-scan/0
  - decoder/rootcheck/0
  - decoder/sca/0
  - decoder/ciscat/0
  - decoder/syscollector-base/0
  - decoder/syscollector-dbsync/0
  - decoder/syscollector-hardware/0
  - decoder/syscollector-hotfix/0
  - decoder/syscollector-netinfo/0
  - decoder/syscollector-network/0
  - decoder/syscollector-network-end/0
  - decoder/syscollector-network-ip/0
  - decoder/syscollector-osinfo/0
  - decoder/syscollector-port/0
  - decoder/syscollector-port-del/0
  - decoder/syscollector-port-save/0
  - decoder/syscollector-process/0
  - decoder/syscollector-process-del/0
  - decoder/syscollector-process-save/0
  - decoder/syscollector-program/0
  - decoder/syscollector-program-del/0
  - decoder/syscollector-program-save/0
  - decoder/dbsync-host-data/0
  - decoder/kvdb-agent-update/0
  - decoder/syscollector-dbsync-host-data/0

  # Upgrade confirmation
  - decoder/upgrade/0

  # Service decoders
  - decoder/syslog/0

outputs:
  - output/file-output/0
